version: "3.8"

services:
  snmp-target:
    build: .
    container_name: snmp-target
    ports:
      - "1161:1611/udp"
    volumes:
      - ./snmpd.conf:/etc/snmp/snmpd.conf:ro
    restart: unless-stopped
  postgres:
    image: postgres:16
    container_name: telemetry-db
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry_pass
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: telemetry-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - postgres

  router1:
    build:
      context: .
      dockerfile: Dockerfile.frr
    container_name: router1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
        - "1162:1611/udp"
    volumes:
      - ./frr-config:/etc/frr
    restart: unless-stopped

volumes:
  pgdata:
  grafanadata:
